# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

from PyQt5.QtWidgets import QApplication, QMainWindow,QDialog

from recorder1 import Recorder
# from ui1 import Ui_MainWindow




class Ui_Dialog(QMainWindow):
    def __init__(self):
        super(Ui_Dialog, self).__init__()

        self.setupUi(self)
        self.retranslateUi(self)
        self.slot_init() # 槽函数设置

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(497, 246)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 100, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 100, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # self.solt()
        #
    def slot_init(self):
        print(1)
        self.pushButton.clicked.connect(self.fun)
        self.pushButton_2.clicked.connect(self.fun1)
    def fun(self):
        rec = Recorder()
        rec.positive()

    def fun1(self):
        main_ui = Ui_MainWindow
        main_ui.show()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "开始录音"))
        self.pushButton_2.setText(_translate("Dialog", "停止录用"))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    ui = Ui_Dialog()
    ui.show()


    exit(app.exec_())